# Generated by Django 6.0.4 on 2026-04-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_main', '0002_student_address_student_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='theme_color',
            field=models.CharField(default='#1e295b', max_length=20),
        ),
    ]
