# Generated by Django 6.0.4 on 2026-04-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_main', '0003_schoolprofile_email_schoolprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='apps_main.teacher'),
        ),
    ]
