# Generated by Django 6.0.4 on 2026-04-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_main', '0006_ensure_default_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='school/signature/'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to='school/stamp/'),
        ),
    ]
