# Generated by Django 6.0.4 on 2026-04-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_main', '0007_schoolprofile_signature_schoolprofile_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='daily_test_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='final_exam_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='midterm_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
