# Generated by Django 6.0.4 on 2026-04-15 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_main', '0008_grade_daily_test_grade_grade_final_exam_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity_note', models.TextField(blank=True, default='')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_main.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='apps_main.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_main.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_main.teacher')),
            ],
            options={
                'unique_together': {('student', 'subject', 'academic_year')},
            },
        ),
    ]
