# Generated by Django 5.1.3 on 2026-04-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_main", "0010_teacher_signature_alter_academicyear_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="program",
            field=models.CharField(
                choices=[
                    ("PAKET_B", "Paket B (SMP)"),
                    ("PAKET_C", "Paket C (SMA)"),
                    ("BOTH", "Keduanya"),
                ],
                default="BOTH",
                max_length=20,
            ),
        ),
    ]
